"""empty message

Revision ID: 14825cfc2018
Revises: 07dbc012779a
Create Date: 2025-08-06 06:39:28.138161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14825cfc2018'
down_revision = '07dbc012779a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('market')
        batch_op.drop_column('primary_exchange')
        batch_op.drop_column('total_employees')
        batch_op.drop_column('share_class_shares_outstanding')
        batch_op.drop_column('locale')
        batch_op.drop_column('homepage_url')
        batch_op.drop_column('list_date')
        batch_op.drop_column('description')
        batch_op.drop_column('sic_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sic_description', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('list_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('homepage_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('locale', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('share_class_shares_outstanding', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_employees', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('primary_exchange', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('market', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
