"""empty message

Revision ID: 314dab1152b0
Revises: 87e4af4b1df4
Create Date: 2025-08-04 09:42:31.044516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '314dab1152b0'
down_revision = '87e4af4b1df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('account_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('CASH', 'INVESTMENT', 'RETIREMENT', name='accounttype'),
               existing_nullable=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('eps', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('dividend_yield', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('beta', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('fifty_day_average', sa.Numeric(precision=15, scale=4), nullable=True))
        batch_op.add_column(sa.Column('two_hundred_day_average', sa.Numeric(precision=15, scale=4), nullable=True))
        batch_op.alter_column('asset_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('STOCK', 'ETF', 'CASH', 'INDEX', name='assettype'),
               existing_nullable=False)

    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('trigger_price', sa.Numeric(precision=15, scale=4), nullable=True))
        batch_op.add_column(sa.Column('commission_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('realized_pnl', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.alter_column('transaction_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('BUY', 'SELL', 'DEPOSIT', 'WITHDRAWAL', 'DIVIDEND', 'INTEREST', 'FEE', name='transactiontype'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='transactionstatus'),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_column('added_at')

    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='transactionstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('transaction_type',
               existing_type=sa.Enum('BUY', 'SELL', 'DEPOSIT', 'WITHDRAWAL', 'DIVIDEND', 'INTEREST', 'FEE', name='transactiontype'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('realized_pnl')
        batch_op.drop_column('commission_fee')
        batch_op.drop_column('trigger_price')
        batch_op.drop_column('order_type')

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('asset_type',
               existing_type=sa.Enum('STOCK', 'ETF', 'CASH', 'INDEX', name='assettype'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('two_hundred_day_average')
        batch_op.drop_column('fifty_day_average')
        batch_op.drop_column('beta')
        batch_op.drop_column('dividend_yield')
        batch_op.drop_column('eps')
        batch_op.drop_column('pe_ratio')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('account_type',
               existing_type=sa.Enum('CASH', 'INVESTMENT', 'RETIREMENT', name='accounttype'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
