"""trial

Revision ID: 87e4af4b1df4
Revises: b947c785cf09
Create Date: 2025-07-31 06:51:26.485084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e4af4b1df4'
down_revision = 'b947c785cf09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('historical_prices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_cap', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('sector', sa.String(length=100), nullable=True))

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('sector')
        batch_op.drop_column('market_cap')

    op.drop_table('historical_prices')
    op.drop_table('users')
    # ### end Alembic commands ###
