"""empty message

Revision ID: 8b77fe06e796
Revises: 14825cfc2018
Create Date: 2025-08-06 08:20:46.184825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b77fe06e796'
down_revision = '14825cfc2018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('exchange_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('list_date', sa.Date(), nullable=True))
        batch_op.drop_column('dividend_yield')
        batch_op.drop_column('market_cap')
        batch_op.drop_column('sector')
        batch_op.drop_column('pe_ratio')
        batch_op.drop_column('eps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eps', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('pe_ratio', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sector', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('market_cap', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dividend_yield', mysql.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.drop_column('list_date')
        batch_op.drop_column('exchange_code')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
