"""empty message

Revision ID: 9edaf1586f86
Revises: 314dab1152b0
Create Date: 2025-08-04 10:43:45.295593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9edaf1586f86'
down_revision = '314dab1152b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('homepage_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sic_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('list_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('market', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('locale', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('primary_exchange', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_employees', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('share_class_shares_outstanding', sa.BigInteger(), nullable=True))
        batch_op.drop_column('fifty_day_average')
        batch_op.drop_column('beta')
        batch_op.drop_column('two_hundred_day_average')

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_hundred_day_average', mysql.DECIMAL(precision=15, scale=4), nullable=True))
        batch_op.add_column(sa.Column('beta', mysql.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('fifty_day_average', mysql.DECIMAL(precision=15, scale=4), nullable=True))
        batch_op.drop_column('share_class_shares_outstanding')
        batch_op.drop_column('total_employees')
        batch_op.drop_column('primary_exchange')
        batch_op.drop_column('locale')
        batch_op.drop_column('market')
        batch_op.drop_column('list_date')
        batch_op.drop_column('sic_description')
        batch_op.drop_column('homepage_url')
        batch_op.drop_column('description')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
