"""empty message

Revision ID: 9f9f9f19ea0f
Revises: 8b77fe06e796
Create Date: 2025-08-06 08:56:17.811286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f9f9f19ea0f'
down_revision = '8b77fe06e796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('account_type')
        batch_op.drop_column('institution')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_type', mysql.ENUM('CASH', 'INVESTMENT', 'RETIREMENT'), nullable=False))

    # ### end Alembic commands ###
