"""Add watchlist and watchlist_item tables

Revision ID: c76c692684fc
Revises: 03916f514f44
Create Date: 2025-07-30 09:24:53.741100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c76c692684fc'
down_revision = '03916f514f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('account_type',
               existing_type=mysql.ENUM('CASH', 'INVESTMENT', 'RETIREMENT'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('institution',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('balance',
               existing_type=mysql.DECIMAL(precision=19, scale=4),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=True)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('asset_type',
               existing_type=mysql.ENUM('STOCK', 'BOND', 'ETF', 'MUTUAL_FUND', 'CRYPTO', 'CASH'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('last_price',
               existing_type=mysql.DECIMAL(precision=19, scale=4),
               type_=sa.Numeric(precision=15, scale=4),
               existing_nullable=True)
        batch_op.alter_column('previous_close_price',
               existing_type=mysql.DECIMAL(precision=19, scale=4),
               type_=sa.Numeric(precision=15, scale=4),
               existing_nullable=True)
        batch_op.alter_column('price_updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('region')

    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.DECIMAL(precision=19, scale=8),
               type_=sa.Numeric(precision=15, scale=4),
               existing_nullable=False)
        batch_op.alter_column('cost_basis',
               existing_type=mysql.DECIMAL(precision=19, scale=4),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=mysql.ENUM('BUY', 'SELL', 'DEPOSIT', 'WITHDRAWAL', 'DIVIDEND', 'INTEREST', 'FEE'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=mysql.DECIMAL(precision=19, scale=8),
               type_=sa.Numeric(precision=15, scale=4),
               existing_nullable=True)
        batch_op.alter_column('price_per_unit',
               existing_type=mysql.DECIMAL(precision=19, scale=4),
               type_=sa.Numeric(precision=15, scale=4),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=19, scale=4),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=mysql.DECIMAL(precision=19, scale=4),
               existing_nullable=False)
        batch_op.alter_column('price_per_unit',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=mysql.DECIMAL(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=mysql.DECIMAL(precision=19, scale=8),
               existing_nullable=True)
        batch_op.alter_column('transaction_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('BUY', 'SELL', 'DEPOSIT', 'WITHDRAWAL', 'DIVIDEND', 'INTEREST', 'FEE'),
               existing_nullable=False)

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.alter_column('cost_basis',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=mysql.DECIMAL(precision=19, scale=4),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=mysql.DECIMAL(precision=19, scale=8),
               existing_nullable=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('price_updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('previous_close_price',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=mysql.DECIMAL(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('last_price',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=mysql.DECIMAL(precision=19, scale=4),
               existing_nullable=True)
        batch_op.alter_column('asset_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('STOCK', 'BOND', 'ETF', 'MUTUAL_FUND', 'CRYPTO', 'CASH'),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=mysql.DECIMAL(precision=19, scale=4),
               nullable=False)
        batch_op.alter_column('institution',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('account_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('CASH', 'INVESTMENT', 'RETIREMENT'),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    op.drop_table('watchlist_items')
    op.drop_table('watchlists')
    # ### end Alembic commands ###
